### ISSUE TITLE
Ontbreken <alt> bij <img> elementen.

### ISSUE THREAD

**Issue by rutgerkock** [Lmikkers/funda#1]
https://github.com/Lmikkers/funda/blob/7912e7782f3894e188c49429e84e03b59050f4ca/index.html#L546-L547

Zie bijvoorbeeld deze regels, voeg een alt tekst toe die de afbeelding beschrijft, om toegankelijkheid te verbeteren.

**Comment by Lmikkers** [comment]
Top dankjewel! Ik heb dit opgelost
